INSERT INTO ITEMS(NAME,PRICE) VALUES('Apple',60.0);
INSERT INTO ITEMS(NAME,PRICE) VALUES('Orange',25.0);

INSERT INTO OFFERS(NAME) VALUES('buyOneGetOneFree');
INSERT INTO OFFERS(NAME) VALUES('threeForThePriceOfTwo');

INSERT INTO CUSTOMERS(NAME,EMAIL) VALUES('cust1','cust1@amex.com');
INSERT INTO CUSTOMERS(NAME,EMAIL) VALUES('cust2','cust2@amex.com');

INSERT INTO OFFER_ITEMS(ITEM_ID,OFFER_ID) VALUES(1,1);
INSERT INTO OFFER_ITEMS(ITEM_ID,OFFER_ID) VALUES(2,2);